# Generated by Django 3.1.1 on 2020-09-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_chat',
            field=models.BooleanField(default=True),
        ),
    ]
